[pytest]
DJANGO_SETTINGS_MODULE = orbitham.settings
python_files = tests.py test_*.py *_test.py
addopts = -ra --strict-markers
testpaths =
    users
    stations
    satellites
    passes
    dashboard
