# Generated by Django 5.2.15 on 2026-06-03 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norad_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(default='amateur', max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('tle_1', models.CharField(max_length=80)),
                ('tle_2', models.CharField(max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'satellites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteTLEHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tle_1', models.CharField(max_length=80)),
                ('tle_2', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tle_history', to='satellites.satellite')),
            ],
            options={
                'db_table': 'satellite_tle_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
